name: Release

concurrency:
  group: release-${{ github.event.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          scope: "@peykio"

      - run: pnpm install

      - run: pnpm build-pg-formatter

      - run: pnpm build

      - name: Create Release Pull Request or Publish Packages
        uses: changesets/action@v1
        with:
          commit: "📦 version packages"
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
